package com.howtodoinjava.demo.chatbot;

import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import org.junit.Assert;
import org.junit.Test;
import java.io.IOException;

public class whenGetRequest_correct {

    @Test
    public void whenGetRequest_thenCorrect() {
        OkHttpClient client = new OkHttpClient();
        Request request = new Request.Builder()
        		// url generated by rapid api for Dublin
        		.url("https://visual-crossing-weather.p.rapidapi.com/history?startDateTime=2019-01-01T00%3A00%3A00&aggregateHours=24&location=Washington%2CDC%2CUSA&endDateTime=2019-01-03T00%3A00%3A00&unitGroup=us&dayStartTime=8%3A00%3A00&contentType=csv&dayEndTime=17%3A00%3A00&shortColumnNames=0")
        		.get()
        		.addHeader("X-RapidAPI-Key", "16648ceb4dmsh7173f54cfdee342p1be6dajsn8282c066674d")
        		.addHeader("X-RapidAPI-Host", "visual-crossing-weather.p.rapidapi.com")
        		.build();
        try {
            Response response = client.newCall(request).execute();
            //when result equals 200 returns correct
            Assert.assertEquals(200, response.code());
        } catch (IOException e) {
            e.printStackTrace();// prints cause of failure
            Assert.fail("An exception occurred during the HTTP request: " + e.getMessage());
        }
    }
}
